search/urls.py
from django.contrib import admin
from django.urls import path

from . import views


app_name = 'search'
urlpatterns = [
    path('get_search/', views.get_search, name='get_search'),  # 首页


]

update_notice/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'update_notice'
urlpatterns = [
    path('update_notice/', views.update_notice, name='update_notice'),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'user'
urlpatterns = [
    # 前台
    # path('login/', views.LoginView.as_view(template_name="login.html"), name='login'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('register/', views.Register.as_view(), name='register'),

    # path('reset_password/<int:pk>/', views.ResetPassword.as_view(), name='reset_password'),
    # path('detail_user/<int:pk>/', views.DetailUser.as_view(), name='detail_user'),  # update_user 代替

    # 后台
    # path('list_user/', views.ListUser.as_view(), name='list_user'),  # 在后台管理中，不需要这个页面
    path('delete_user/<int:pk>/', views.DeleteUser.as_view(), name='delete_user'),
    path('update_user/<int:pk>/', views.UpdateUser.as_view(), name='update_user'),

    # path('<int:pk>/password/', views.PasswordChangeView.as_view(), name='password_change'),

    # path('update_user/<int:pk>/', views.user_profile, name='update_user'),

]

web/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'web'
urlpatterns = [
    # TODO url update
    path('', views.ListNoteGroup.as_view(), name='index'),  # 首页
    # group页面
    path('add_note_groups/', views.AddNoteGroup.as_view(), name='add_note_groups'),
    path('update_note_groups/<int:pk>/', views.UpdateNoteGroup.as_view(), name='update_note_groups'),
    path('delete_note_groups/<int:pk>/', views.DeleteNoteGroup.as_view(), name='delete_note_groups'),

    path('fast_notes/', views.NoteFastList.as_view(), name='fast_notes'),
    # note页面
    path('note_groups/<int:pk_group>/', include([
        path('notes/', views.ListNotes.as_view(), name='notes'),
        path('add_notes/', views.AddNotes.as_view(), name='add_notes'),
        path('delete_notes/<int:pk>/', views.DeleteNotes.as_view(), name='delete_notes'),
        path('modify_notes/<int:pk>/', views.UpdateNotes.as_view(), name='modify_notes'),


    ])),



]

zd_note/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # 需要添加app_name
    path('search/', include('search.urls', namespace='search')),
    path('update_notice/', include('update_notice.urls', namespace='update_notice')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('web.urls', namespace='web')),
    # path('jobs/', include('jobs.urls', namespace='jobs')),

    # path('search/', include(('search.urls', 'search'), namespace='search')),
    # path('update_notice/', include(('update_notice.urls', 'update_notice'), namespace='update_notice')),
    # path('user/', include(('user.urls', 'user'), namespace='user')),
    # path('', include(('web.urls', 'web'), namespace='web')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 开发期间提供media

web/models.py
from django.db import models
from utils.base_model import BaseModel

from user.models import User
# from django.contrib.auth.models import AbstractUser, User


# def get_default_user():
#     return User.objects.get(pk=4)


class NoteGroup(BaseModel):
    name = models.CharField(max_length=20, verbose_name='组名')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')

    def __str__(self):
        return f'{self.user}-{self.name}'
        # return f'{self.name}'


class Note(BaseModel):
    title = models.CharField(max_length=20, verbose_name='题目')
    content = models.TextField(verbose_name='内容')
    note_group = models.ForeignKey(NoteGroup, on_delete=models.SET_NULL, verbose_name='属组', null=True, blank=True)
    # 默认反向关联为 小写类名_set 可以自定义
    # note_group = models.ForeignKey('NoteGroup', on_delete=models.SET_NULL, verbose_name='属组', null=True, blank=True, related_name='notes')
    is_fast = models.BooleanField(verbose_name='快速访问', default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')

    def __str__(self):
        return f'{self.note_group}-{self.title}'
        # return f'{self.note_group}-{self.title}'


# models.Manager
# models.Model

templates/base.html
{% load static %}
<!DOCTYPE html>
{#<html lang="en">#}
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Ensures optimal rendering on mobile devices. -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-4.6.2/css/bootstrap.css' %}">
    {% block css %}
    {% endblock css %}
    <title>
        {% block title %}
            Zd 笔记
        {% endblock title %}
    </title>
</head>
<body>
<div class="container-fluid">
{#<div class="container">#}
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'web:index' %}">ZdNote</a>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="navbar-nav">
{#                        <li class="nav-item active">#}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'web:index' %}">分组列表<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'web:fast_notes' %}">快速访问</a>
                        </li>
{#                        <li class="nav-item">#}
{#                            <a class="nav-link" href="{% url 'user:list_user' %}">用户列表</a>#}
{#                        </li>#}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'update_notice:update_notice' %}">更新公告</a>
                        </li>
                        {#                        <li class="nav-item dropdown">#}
                        {#                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"#}
                        {#                               data-toggle="dropdown">Dropdown link</a>#}
                        {#                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">#}
                        {#                                <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another#}
                        {#                                action</a> <a class="dropdown-item" href="#">Something else here</a>#}
                        {#                                <div class="dropdown-divider">#}
                        {#                                </div>#}
                        {#                                <a class="dropdown-item" href="#">Separated link</a>#}
                        {#                            </div>#}
                        {#                        </li>#}
                    </ul>
                    <form class="form-inline" action="{% url 'search:get_search' %}">
                        <input name="q" class="form-control mr-sm-2" type="text" placeholder="搜索笔记"/>
                        <button class="btn btn-primary my-2 my-sm-0" type="submit">
                            搜索
                        </button>
                    </form>
                    <ul class="navbar-nav ml-md-auto">
                        {% if not user.is_authenticated  %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:register' %}">注册 <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'user:login' %}">登录 <span class="sr-only">(current)</span></a>
                        </li>
                        {% else %}

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                               data-toggle="dropdown">{{ user }}</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'user:update_user' user.pk %}">个人信息</a>
{#                                <a class="dropdown-item" href="#">Another action</a>#}
{#                                <a class="dropdown-item" href="#">Something else here</a>#}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'user:logout' %}">退出</a>
{#                                <a class="dropdown-item" href="{% url 'user:delete_user' user.pk %}">删除账号</a>#}
                            </div>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>

{#            <blockquote class="blockquote">#}
{#                <p class="mb-0">#}
{#                    A good memory is not better than a bad pen.#}
{#                </p>#}
{#                <footer class="blockquote-footer">#}
{#                    Zhenda in <cite>Shenzhen</cite>#}
{#                </footer>#}
{#            </blockquote>#}

        </div>
    </div>

    <div class="row" style="padding-top: 80px">
{#    <div class="row">#}
        {% block all_content %}
{#            <div class="col-md-3">#}
{#                {% block sidebar %}#}
{#                    <ul>#}
{#                        <li class="list-item">#}
{#                            Lorem ipsum dolor sit amet#}
{#                            <small>-->3</small>#}
{#                        </li>#}
{#                        <li class="list-item">#}
{#                            Consectetur adipiscing elit#}
{#                            <small>-->13</small>#}
{#                        </li>#}
{#                        <li class="list-item">#}
{#                            Integer molestie lorem at massa#}
{#                            <small>-->31</small>#}
{#                        </li>#}
{#                    </ul>#}
{##}
{#                {% endblock sidebar %}#}
{#            </div>#}
{#            <div class="col-md-9">#}
            <div class="col-md-12">
{#                <div class="page-header">#}
{#                    <h1>#}
{#                        主要内容#}
{#                    </h1>#}
{#                </div>#}
                <br>
                {% block content %}
                    {#            <nav>#}
                    {#                <ol class="breadcrumb">#}
                    {#                    <li class="breadcrumb-item">#}
                    {#                        <a href="#">Home</a>#}
                    {#                    </li>#}
                    {#                    <li class="breadcrumb-item">#}
                    {#                        <a href="#">Library</a>#}
                    {#                    </li>#}
                    {#                    <li class="breadcrumb-item active">#}
                    {#                        Data#}
                    {#                    </li>#}
                    {#                </ol>#}
                    {#            </nav>#}


                    <h3>
                        分组表
                    </h3>
                    <a type="button" class="btn btn-success" href="{% url 'web:add_note_groups' %}">
                        添加分组
                    </a>

                    <div class="table-responsive">
                        <table class="table table-hover table-bordered table-striped">
                            <thead>
                            <tr>

                                <th>
                                    id
                                </th>
                                <th>
                                    组名
                                </th>
                                <th>
                                    个数
                                </th>
                                <th>
                                    操作
                                </th>

                            </tr>
                            </thead>
                            <tbody>
                            {% for i in note_groups %}
                                <tr>
                                    <td>
                                        {{ i.id }}
                                    </td>
                                    <td>
                                        {{ i.name }}
                                    </td>
                                    <td>
                                        {{ i.note_set.count }}
                                    </td>
                                    <td>
                                        <a type="button" class="btn btn-primary btn-sm" href="{% url 'web:notes' i.id %}">
                                            进入
                                        </a>
                                        <a type="button" class="btn btn-warning btn-sm" href="{% url 'web:update_note_groups' i.id %}">
                                            修改
                                        </a>
                                        <a type="button" class="btn btn-danger btn-sm" href="{% url 'web:delete_note_groups' i.id %}">
                                            删除
                                        </a>
                                    </td>

                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>

                {% endblock content %}
            </div>

        {% endblock all_content %}
    </div>
    <div class="row">
        <div class="col-md-12" style="text-align: center">
            <hr/>
            <address>
                <strong>zhenda</strong> at shenzhen
                <br/>
                <abbr title="Phone">Phone:</abbr> 15135376773
            </address>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'plugins/bootstrap-4.6.2/js/bootstrap.bundle.js' %}"></script>
{% block js %}
{% endblock js %}
</body>
</html>

templates/base_form_inline.html
<form method="post">
    {% csrf_token %}
    <h3>{{ form_title }}</h3>
    {% block context %}
    {{ form.as_p }}
    {% endblock context %}
    <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary">返回</a>{# 返回之前页面 #}
{#    <input type="submit" value="提交" class="btn btn-warning">#}
    <button type="submit" class="btn btn-warning">提交</button>
</form>

templates/base_form_inline_delete.html
{% extends 'base_form_inline.html' %}
    {% block context %}
    <p>确认删除 {{ object }} ？</p>
    {% endblock context %}

templates/demo2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="stylesheet" href="{% static 'plugins/bootstrap-4.6.2/css/bootstrap.css' %}">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    {% block css %}
    {% endblock css %}
    <title>
        {% block title %}
            首页
        {% endblock title %}
    </title>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="#">zd记事本</a>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                               data-toggle="dropdown">Dropdown link</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another
                                action</a> <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                    <form class="form-inline">
                        <input class="form-control mr-sm-2" type="text"/>
                        <button class="btn btn-primary my-2 my-sm-0" type="submit">
                            Search
                        </button>
                    </form>
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                               data-toggle="dropdown">Dropdown link</a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another
                                action</a> <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider">
                                </div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <span class="badge badge-default">Label</span>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">Library</a>
                    </li>
                    <li class="breadcrumb-item active">
                        Data
                    </li>
                </ol>
            </nav>
            <div class="page-header">
                <h1>
                    LayoutIt! <small>Interface Builder for Bootstrap</small>
                </h1>
            </div>
            <p>
                Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Aliquam eget sapien sapien.
                Curabitur in metus urna. In hac habitasse platea dictumst. Phasellus eu sem sapien, sed vestibulum
                velit. Nam purus nibh, lacinia non faucibus et, pharetra in dolor. Sed iaculis posuere diam ut cursus.
                <em>Morbi commodo sodales nisi id sodales. Proin consectetur, nisi id commodo imperdiet, metus nunc
                    consequat lectus, id bibendum diam velit et dui.</em> Proin massa magna, vulputate nec bibendum nec,
                posuere nec lacus. <small>Aliquam mi erat, aliquam vel luctus eu, pharetra quis elit. Nulla euismod
                ultrices massa, et feugiat ipsum consequat eu.</small>
            </p>
        </div>
        <div class="col-md-4">
            <span class="badge badge-default">Label</span>
            <ul>
                <li class="list-item">
                    Lorem ipsum dolor sit amet
                </li>
                <li class="list-item">
                    Consectetur adipiscing elit
                </li>
                <li class="list-item">
                    Integer molestie lorem at massa
                </li>
                <li class="list-item">
                    Facilisis in pretium nisl aliquet
                </li>
                <li class="list-item">
                    Nulla volutpat aliquam velit
                </li>
                <li class="list-item">
                    Faucibus porta lacus fringilla vel
                </li>
                <li class="list-item">
                    Aenean sit amet erat nunc
                </li>
                <li class="list-item">
                    Eget porttitor lorem
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">

            <address>
                <strong>Twitter, Inc.</strong><br/> 795 Folsom Ave, Suite 600<br/> San Francisco, CA 94107<br/> <abbr
                    title="Phone">P:</abbr> (123) 456-7890
            </address>
        </div>
    </div>

{#<script src="{% static 'js/jquery.js' %}"></script>#}
{#<script src="{% static 'plugins/bootstrap-4.6.2/js/bootstrap.bundle.js' %}"></script>#}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% block js %}
{% endblock js %}
</body>
</html>

templates/demooo.html
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<ul class="nav nav-pills">
				<li class="nav-item">
					 <a class="nav-link btn btn-primary" href="#">Home <span class="badge badge-light">42</span></a>
				</li>
				<li class="nav-item">
					 <a class="nav-link" href="#">More <span class="badge badge-secondary">16</span></a>
				</li>
			</ul>
			<div class="jumbotron">
				<h2>
					Hello, world!
				</h2>
				<p>
					This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="#">Learn more</a>
				</p>
			</div>
		</div>
	</div>
	<div class="row">

	</div>
</div>