web/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views


app_name = 'web'
urlpatterns = [
    # TODO url update
    path('', views.ListNoteGroup.as_view(), name='index'),  # 首页
    # group页面
    path('add_note_groups/', views.AddNoteGroup.as_view(), name='add_note_groups'),
    path('update_note_groups/<int:pk>/', views.UpdateNoteGroup.as_view(), name='update_note_groups'),
    path('delete_note_groups/<int:pk>/', views.DeleteNoteGroup.as_view(), name='delete_note_groups'),

    path('fast_notes/', views.NoteFastList.as_view(), name='fast_notes'),
    # note页面
    path('note_groups/<int:pk_group>/', include([
        path('notes/', views.ListNotes.as_view(), name='notes'),
        path('add_notes/', views.AddNotes.as_view(), name='add_notes'),
        path('delete_notes/<int:pk>/', views.DeleteNotes.as_view(), name='delete_notes'),
        path('modify_notes/<int:pk>/', views.UpdateNotes.as_view(), name='modify_notes'),


    ])),



]

zd_note/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    # 需要添加app_name
    path('search/', include('search.urls', namespace='search')),
    path('update_notice/', include('update_notice.urls', namespace='update_notice')),
    path('user/', include('user.urls', namespace='user')),
    path('', include('web.urls', namespace='web')),
    # path('jobs/', include('jobs.urls', namespace='jobs')),

    # path('search/', include(('search.urls', 'search'), namespace='search')),
    # path('update_notice/', include(('update_notice.urls', 'update_notice'), namespace='update_notice')),
    # path('user/', include(('user.urls', 'user'), namespace='user')),
    # path('', include(('web.urls', 'web'), namespace='web')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 开发期间提供media

web/templates/web/add_group.html
{% extends 'base.html' %}

{% block content %}
{% include 'base_form_inline.html' %}
{#    {{ block.super }}#}


{% endblock content %}

web/templates/web/add_note.html
{% extends 'web/notes.html' %}

{% block content %}

    {% include 'base_form_inline.html' %}

{% endblock content %}

web/templates/web/delete_group.html
{% extends 'base.html' %}


{% block content %}
{% include 'base_form_inline_delete.html' %}



{% endblock content %}

web/templates/web/delete_note.html
{% extends 'web/notes.html' %}


{% block content %}
    {% include 'base_form_inline_delete.html' %}
{#    <h3>#}
{#        h3. Lorem ipsum dolor sit amet.#}
{#    </h3>#}
{#    <p>#}
{#        Lorem ipsum dolor sit amet, <strong>consectetur adipiscing elit</strong>. Aliquam eget sapien sapien.#}
{#        Curabitur in metus urna. In hac habitasse platea dictumst. Phasellus eu sem sapien, sed vestibulum#}
{#        velit. Nam purus nibh, lacinia non faucibus et, pharetra in dolor. Sed iaculis posuere diam ut cursus.#}
{#        <em>Morbi commodo sodales nisi id sodales. Proin consectetur, nisi id commodo imperdiet, metus nunc#}
{#            consequat lectus, id bibendum diam velit et dui.</em> Proin massa magna, vulputate nec bibendum nec,#}
{#        posuere nec lacus. <small>Aliquam mi erat, aliquam vel luctus eu, pharetra quis elit. Nulla euismod#}
{#        ultrices massa, et feugiat ipsum consequat eu.</small>#}
{#    </p>#}
{% endblock content %}

web/templates/web/note_fast_list.html
{% extends 'base.html' %}

{% block title %}
    快速访问笔记页面
{% endblock title %}

{% block content %}
    <h3>
        快速访问笔记页面
{#        {{ request.path }}--{{ request.build_absolute_uri }}#}
    </h3>
    <div class="table-responsive">
        <table class="table table-hover table-bordered table-striped">
            <thead>
            <tr>

                <th>
                    id
                </th>
                <th>
                    所属组名
                </th>
                <th>
                    题目
                </th>
                <th>
                    内容
                </th>
                <th>
                    快速访问
                </th>
                <th>
                    操作
                </th>


            </tr>
            </thead>
            <tbody>
            {% for i in notes %}
                <tr>
                    <td>
                        {{ i.id }}
                    </td>
                    <td>
                        {{ i.note_group }}
                    </td>
                    <td>
                        {{ i.title }}
                    </td>
                    <td>
                        {{ i.content }}
                    </td>
                    <td>
                        {{ i.is_fast }}
                    </td>

                    <td>

                        <a type="button" class="btn btn-warning btn-sm" href="{% url 'web:modify_notes' i.note_group_id i.id %}">
                            修改
                        </a>
                        <a type="button" class="btn btn-primary btn-sm" href="{% url 'web:notes' i.note_group_id %}">
                            进入组
                        </a>
                    </td>

                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>


{% endblock content %}

web/templates/web/notes.html
{% extends 'base.html' %}

{% block title %}
    {{ group_obj }}组-笔记页面
{% endblock title %}

{% block content %}
    <h3>
        {{ group_obj }}组-笔记表
{#        {{ request.path }}--{{ request.build_absolute_uri }}#}
    </h3>
    <a type="button" class="btn btn-success" href="{% url 'web:add_notes' group_pk %}">
        添加笔记
    </a>

    <div class="table-responsive">
        <table class="table table-hover table-bordered table-striped">
            <thead>
            <tr>

                <th>
                    id
                </th>
                <th>
                    题目
                </th>
                <th>
                    内容
                </th>
                <th>
                    快速访问
                </th>
                <th>
                    操作
                </th>


            </tr>
            </thead>
            <tbody>
            {% for i in notes %}
                <tr>
                    <td>
                        {{ i.id }}
                    </td>
                    <td>
                        {{ i.title }}
                    </td>
                    <td>
                        {{ i.content }}
                    </td>
                    <td>
                        {{ i.is_fast }}
                    </td>

                    <td>
    {#                    <a type="button" class="btn btn-primary btn-sm" href="{% url 'web:notes' i.id %}">#}
    {#                        进入#}
    {#                    </a>#}
                        <a type="button" class="btn btn-warning btn-sm" href="{% url 'web:modify_notes' group_pk i.id %}">
                            修改
                        </a>
                        <a type="button" class="btn btn-danger btn-sm" href="{% url 'web:delete_notes' group_pk i.id %}">
                            删除
                        </a>
                    </td>

                </tr>
            {% endfor %}


            </tbody>
        </table>
    </div>


{% endblock content %}